### PR TITLE
Assignment 6.2 Quickstart

### PR DESCRIPTION
**Pull request by alkreb**
Adds a new quickstart page to the docs

### CODE REVIEW

**Comment by rbwatson** [comment]
Hi Alicia,
I'm unable to merge this PR because it has merge commits in it.

While merge commits integrate recent changes from the `main` branch into your PR (feature) branch, they do so in a way that changes the history (by combining the new commits into a single summary of those commits.) The correct way to update your feature branch is to use the **rebase and merge** option to update your feature branch.

If you need any help sorting this out, let me know.

**Review by rbwatson — CHANGES_REQUESTED** [review]
The PR needs work before it can be merged.

**Comment by alkreb** [comment]
what do I need to do?

**Comment by rbwatson** [comment]
I think the easiest path to take would be to:
1. In the GitHub website, Update your fork.
2. In the GitHub desktop, create a new feature branch from `main`.
4. Select your PR/feature branch.
5. Select the commit from your PR branch with your changes (Commit `9b5640a`). Don't select any of the merge commits or any other commits.
6. [Cherry-pick that commit](https://docs.github.com/en/desktop/managing-commits/cherry-picking-a-commit-in-github-desktop) from your PR branch (Commit `9b5640a`) to your new feature branch.
7. Review the changes in your new feature branch. Build and test the docs that build from your new feature branch.
8. After everything looks good, open a new PR from the new feature branch.
9. Update this PR with a new comment that contains the link to your new PR.
10. Let me know at this point and I'll take it from there.

I tried this from my account and it seemed to work. Because you have only one commit with your changes and it doesn't have any conflicts, it should be able to be cherry-picked from the current branch to a new one without any problems.

You can do this .

**Comment by alkreb** [comment]
Here's the link to the new PR: https://github.com/UWC2-APIDOC/to-do-service-au24/pull/50

**Pull request closed without merging**
